---
- name: check valid command
  hosts: localhost
  tasks: 
          
    - name: List of commands
      set_fact:
        commands:
          - pwd
          - ls -l
          - ps -ef
          - df -h
          - top
          - smv
          - psm

    - name: Run list of commands
      ansible.builtin.command: "{{item}}"
      loop: "{{commands}}"
      register: command_output
      ignore_errors: yes

    - name: Define result list
      set_fact:
          valid: []
          invalid: []

    - name: Add valid commands
      set_fact:
        valid: "{{ valid + [item.item] }}"
      loop: "{{ command_output.results }}"
      when: item.rc == 0

    - name: Add invalid commands
      set_fact:
        invalid: "{{ invalid + [item.item] }}"
      loop: "{{ command_output.results }}"
      when: item.rc != 0


    - name: Display valid commands
      ansible.builtin.debug:
       msg: "Valid Commands: {{ valid }}"

    - name: Display invalid commands
      ansible.builtin.debug:
        msg: "Invalid Commands: {{ invalid }}"